# PostgreSQL configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/todoapp}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:arko1234}

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# (Optional) Disable H2 console
spring.h2.console.enabled=false
